### ISSUE TITLE
Add to the documentation that you need to restart the idea for the plugin to work properly

### ISSUE THREAD

**Issue by RazerFord** [SuduIDE/ij-textmate#15]
After installation saving Injection doesn't work without plugin reload

**Comment by yeswolf** [comment]
@RazerFord Are we sure we cannot make them saved without restart? From the first glance it looks like we should be able to do that.

**Comment by RazerFord** [comment]
> @RazerFord Are we sure we cannot make them saved without restart? From the first glance it looks like we should be able to do that.

Updated. Here I meant that after installing the plugin, you need to restart the idea

**Comment by yeswolf** [comment]
@RazerFord I've meant, that in general there should be a reason for the restart. Do we understand the reason? Cause in general plugin is just loaded, and no restart is required.

**Comment by RazerFord** [comment]
> @RazerFord I've meant, that in general there should be a reason for the restart. Do we understand the reason? Cause in general plugin is just loaded, and no restart is required.

I have a hypothesis that it is because I have persistent storage registered only in plugin.xml, if I would register it in code, I don't think I would have this problem
